from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, Optional


SHIFT_KEYCODES = {"KEY_LEFTSHIFT", "KEY_RIGHTSHIFT"}
KANA_TOGGLE_KEYCODES = {"KEY_KANA", "KEY_KATAKANA", "KEY_HIRAGANA", "KEY_KATAKANAHIRAGANA"}

@dataclass(frozen=True)
class KeyMapper:
    unshifted: Dict[str, str]
    shifted: Dict[str, str]
    kana_unshifted: Dict[str, str] = field(default_factory=dict)
    kana_shifted: Dict[str, str] = field(default_factory=dict)
    
    # キーコードと状態から送信文字を引き当てる。
    def map_keycode(self, keycode: str, shift: bool, *, kana: bool = False) -> Optional[str]:
        """シフト/かな状態を考慮してキーコードを文字に変換する。"""
        if kana:
            # かなモード時はシフト有無に応じたマッピングを優先する。
            mapped = self.kana_shifted.get(keycode) if shift else self.kana_unshifted.get(keycode)
            if mapped is not None:
                return mapped
            # かなのシフト表に無ければ通常のかな表へフォールバックする。
            fallback = self.kana_unshifted.get(keycode)
            if fallback is not None:
                return fallback
        if shift:
            return self.shifted.get(keycode) or self.unshifted.get(keycode)
        return self.unshifted.get(keycode)


DEFAULT_KEYMAP = KeyMapper(
    unshifted={
        "KEY_SPACE": " ",
        "KEY_MINUS": "-",
        "KEY_EQUAL": "=",
        "KEY_LEFTBRACE": "[",
        "KEY_RIGHTBRACE": "]",
        "KEY_BACKSLASH": "\\",
        "KEY_YEN": "¥",
        "KEY_RO": "\\",
        "KEY_SEMICOLON": ";",
        "KEY_APOSTROPHE": "'",
        "KEY_GRAVE": "`",
        "KEY_COMMA": ",",
        "KEY_DOT": ".",
        "KEY_SLASH": "/",
        "KEY_1": "1",
        "KEY_2": "2",
        "KEY_3": "3",
        "KEY_4": "4",
        "KEY_5": "5",
        "KEY_6": "6",
        "KEY_7": "7",
        "KEY_8": "8",
        "KEY_9": "9",
        "KEY_0": "0",
        "KEY_A": "a",
        "KEY_B": "b",
        "KEY_C": "c",
        "KEY_D": "d",
        "KEY_E": "e",
        "KEY_F": "f",
        "KEY_G": "g",
        "KEY_H": "h",
        "KEY_I": "i",
        "KEY_J": "j",
        "KEY_K": "k",
        "KEY_L": "l",
        "KEY_M": "m",
        "KEY_N": "n",
        "KEY_O": "o",
        "KEY_P": "p",
        "KEY_Q": "q",
        "KEY_R": "r",
        "KEY_S": "s",
        "KEY_T": "t",
        "KEY_U": "u",
        "KEY_V": "v",
        "KEY_W": "w",
        "KEY_X": "x",
        "KEY_Y": "y",
        "KEY_Z": "z",
    },
    shifted={
        "KEY_MINUS": "_",
        "KEY_EQUAL": "+",
        "KEY_LEFTBRACE": "{",
        "KEY_RIGHTBRACE": "}",
        "KEY_BACKSLASH": "|",
        "KEY_YEN": "|",
        "KEY_RO": "_",
        "KEY_SEMICOLON": ":",
        "KEY_APOSTROPHE": '"',
        "KEY_GRAVE": "~",
        "KEY_COMMA": "<",
        "KEY_DOT": ">",
        "KEY_SLASH": "?",
        "KEY_1": "!",
        "KEY_2": "@",
        "KEY_3": "#",
        "KEY_4": "$",
        "KEY_5": "%",
        "KEY_6": "^",
        "KEY_7": "&",
        "KEY_8": "*",
        "KEY_9": "(",
        "KEY_0": ")",
        "KEY_A": "A",
        "KEY_B": "B",
        "KEY_C": "C",
        "KEY_D": "D",
        "KEY_E": "E",
        "KEY_F": "F",
        "KEY_G": "G",
        "KEY_H": "H",
        "KEY_I": "I",
        "KEY_J": "J",
        "KEY_K": "K",
        "KEY_L": "L",
        "KEY_M": "M",
        "KEY_N": "N",
        "KEY_O": "O",
        "KEY_P": "P",
        "KEY_Q": "Q",
        "KEY_R": "R",
        "KEY_S": "S",
        "KEY_T": "T",
        "KEY_U": "U",
        "KEY_V": "V",
        "KEY_W": "W",
        "KEY_X": "X",
        "KEY_Y": "Y",
        "KEY_Z": "Z",
    },
    kana_unshifted={
        "KEY_SPACE": " ",
        "KEY_1": "ﾇ",
        "KEY_2": "ﾌ",
        "KEY_3": "ｱ",
        "KEY_4": "ｳ",
        "KEY_5": "ｴ",
        "KEY_6": "ｵ",
        "KEY_7": "ﾔ",
        "KEY_8": "ﾕ",
        "KEY_9": "ﾖ",
        "KEY_0": "ﾜ",
        "KEY_MINUS": "ﾎ",
        "KEY_EQUAL": "ﾍ",
        "KEY_BACKSLASH": "ｰ",
        "KEY_YEN": "ｰ",
        "KEY_Q": "ﾀ",
        "KEY_W": "ﾃ",
        "KEY_E": "ｲ",
        "KEY_R": "ｽ",
        "KEY_T": "ｶ",
        "KEY_Y": "ﾝ",
        "KEY_U": "ﾅ",
        "KEY_I": "ﾆ",
        "KEY_O": "ﾗ",
        "KEY_P": "ｾ",
        "KEY_LEFTBRACE": "ﾞ",
        "KEY_RIGHTBRACE": "ﾟ",
        "KEY_A": "ﾁ",
        "KEY_S": "ﾄ",
        "KEY_D": "ｼ",
        "KEY_F": "ﾊ",
        "KEY_G": "ｷ",
        "KEY_H": "ｸ",
        "KEY_J": "ﾏ",
        "KEY_K": "ﾉ",
        "KEY_L": "ﾘ",
        "KEY_SEMICOLON": "ﾚ",
        "KEY_APOSTROPHE": "ｹ",
        "KEY_Z": "ﾂ",
        "KEY_X": "ｻ",
        "KEY_C": "ｿ",
        "KEY_V": "ﾋ",
        "KEY_B": "ｺ",
        "KEY_N": "ﾐ",
        "KEY_M": "ﾓ",
        "KEY_COMMA": "ﾈ",
        "KEY_DOT": "ﾙ",
        "KEY_SLASH": "ﾒ",
        "KEY_RO": "ﾛ",
    },
    kana_shifted={
        "KEY_3": "ｧ",
        "KEY_4": "ｩ",
        "KEY_5": "ｪ",
        "KEY_6": "ｫ",
        "KEY_7": "ｬ",
        "KEY_8": "ｭ",
        "KEY_9": "ｮ",
        "KEY_0": "ｦ",
        "KEY_Z": "ｯ",
        "KEY_SLASH": "･",
    },
)
